name: knectar
favicon: null
layout_spectrum: 0.9188128288369626
typography_spectrum: 0.5141384499147534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9470682030078024
  lightness: 0.9034003790002316
  saturation: 0.030245702248066664
  rhythmicContrast: 0.8807702702470124
purpose: []
